version: "3.9"
services:
  selenium:
    # container_name: selenium_chrome
    # image: selenium/standalone-chrome
    container_name: selenium_edge
    image: selenium/node-edge
    ports:
      - 4444:4444
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 3000
      GRID_TIMEOUT: 3000
