version: "3.9"
services:
  #selenium:
  #  container_name: selenium_chrome
  #  image: selenium/standalone-chrome
  #  ports:
  #    - 4444:4444
  #  environment:
  #    GRID_MAX_SESSION: 16
  #    GRID_BROWSER_TIMEOUT: 3000
  #    GRID_TIMEOUT: 3000



  selenium-hub:
    image: selenium/hub:latest
    ports:
      - '4442:4442'
      - '4443:4443'
      - '4444:4444'
  selenium:
    container_name: selenium_edge
    image: selenium/node-edge
    ports:
      - 4444:4444
    environment:
      SE_EVENT_BUS_HOST: hub
      SE_EVENT_BUS_PUBLISH_PORT: 4442
      SE_EVENT_BUS_SUBSCRIBE_PORT: 4443
      SE_NODE_GRID_URL: http://localhost:4444    
